#!/bin/sh

version=$1

url="https://s3.amazonaws.com/Minecraft.Download/versions/$version/minecraft_server.$version.jar"

curl -# -o ./minecraft_server.jar $url

if [ ! -e ./minecraft_server.jar ]; then
    exit 1
fi
