#!/bin/sh
# Special variable
## EULA
if [ ! -e "./eula.txt" ]; then 
    eula=${EULA:-false}
    if [ "$eula" = "true" ]; then
        echo "eula=$eula" > "./eula.txt"
    fi
fi

## OPS
for op in $(echo $OPS | tr ',' ' ');do
    cat ops.txt 2> /dev/null | grep "^$op$" > /dev/null
    if [ $? -ne 0 ]; then
        echo $op >> ./ops.txt
    fi
done

# setenv
do_find() {
    find=$(which find)
    targets="*.txt server.properties *.json $(echo $SETENV_TARGET | tr ',' ' ')"
    echo $targets | tr ' ' '\n' | while read i; do
        find . -name $i
    done
}

do_find | while read i; do
    
    if [ "$(grep "#" $i| wc -l | awk '{print $1}')" = "0" ]; then
        continue
    fi

    cat $i | while read j; do
        j=$(echo $j | sed -e "s/#/\\\\#/g")
        eval echo $j >> "$i.tmp"
    done

    if [ -e "$i.tmp" ]; then
        mv $i.tmp $i
    fi
done

exit 0
