#!/bin/sh

version=$1

url="http://files.minecraftforge.net/maven/net/minecraftforge/forge/$version/forge-$version-installer.jar"

curl -# -o ./installer.jar $url

java -jar ./installer.jar --installServer > /dev/null 2>&1

mv ./forge-$version-universal.jar ./minecraft_server.jar

