#!/bin/sh

id=$(docker info | grep Username | awk '{ print $2"/" }')
cmd=$1

gettag() {
    echo $id"minecraft:$1"
}

build() {
    version=$1
    target=$2
    tag=$(gettag $version)
    docker build -t $tag $target
    return 0
}

targets() {
    target=$1
    ls | grep $target | sed -e "s/$target//g" | sort -r | while read f; do
        path=$(pwd)/$target$f
        
        if [ -e "$path/Dockerfile" ]; then
            echo $f $path
        fi

    done
}

main(){

    targets vanilla- | while read f; do
        ret=($f)
        build ${ret[0]} ${ret[1]}
    done
    
    targets forge- | while read f; do
        ret=($f)
        build forge-${ret[0]} ${ret[1]}
    done

}

main
